/// Appointment Model
///
/// Data model that extends AppointmentEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/appointment_entity.dart';

/// Appointment data model with JSON serialization
class AppointmentModel extends AppointmentEntity {
  const AppointmentModel({
    required super.patientId,
    required super.doctorId,
    required super.departmentId,
    required super.branchId,
    required super.familyMemberId,
    required super.appointmentDate,
    required super.slotStartTime,
    required super.slotEndTime,
    required super.bookingSource,
    required super.appointmentType,
    required super.visitReason,
    required super.chiefComplaint,
    required super.priority,
    required super.status,
    required super.cancellationReason,
    required super.cancelledBy,
    required super.tokenNumber,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => '$patientId-$doctorId-$appointmentDate-$slotStartTime';

  /// Creates a AppointmentModel from JSON map
  factory AppointmentModel.fromJson(Map<String, dynamic> json) {
    return AppointmentModel(
      patientId: json['patient_id']?.toString() ?? '',
      doctorId: json['doctor_id']?.toString() ?? '',
      departmentId: json['department_id']?.toString() ?? '',
      branchId: json['branch_id']?.toString() ?? '',
      familyMemberId: json['family_member_id']?.toString() ?? '',
      appointmentDate: json['appointment_date']?.toString() ?? '',
      slotStartTime: json['slot_start_time']?.toString() ?? '',
      slotEndTime: json['slot_end_time']?.toString() ?? '',
      bookingSource: json['booking_source']?.toString() ?? '',
      appointmentType: json['appointment_type']?.toString() ?? '',
      visitReason: json['visit_reason']?.toString() ?? '',
      chiefComplaint: json['chief_complaint']?.toString() ?? '',
      priority: json['priority']?.toString() ?? '',
      status: json['status']?.toString() ?? '',
      cancellationReason: json['cancellation_reason']?.toString() ?? '',
      cancelledBy: json['cancelled_by']?.toString() ?? '',
      tokenNumber: json['token_number'] as int? ?? 0,
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'patient_id': patientId,
      'doctor_id': doctorId,
      'department_id': departmentId,
      'branch_id': branchId,
      'family_member_id': familyMemberId,
      'appointment_date': appointmentDate,
      'slot_start_time': slotStartTime,
      'slot_end_time': slotEndTime,
      'booking_source': bookingSource,
      'appointment_type': appointmentType,
      'visit_reason': visitReason,
      'chief_complaint': chiefComplaint,
      'priority': priority,
      'status': status,
      'cancellation_reason': cancellationReason,
      'cancelled_by': cancelledBy,
      'token_number': tokenNumber,
    };
  }

  /// Creates a AppointmentModel from a AppointmentEntity
  factory AppointmentModel.fromEntity(AppointmentEntity entity) {
    return AppointmentModel(
      patientId: entity.patientId,
      doctorId: entity.doctorId,
      departmentId: entity.departmentId,
      branchId: entity.branchId,
      familyMemberId: entity.familyMemberId,
      appointmentDate: entity.appointmentDate,
      slotStartTime: entity.slotStartTime,
      slotEndTime: entity.slotEndTime,
      bookingSource: entity.bookingSource,
      appointmentType: entity.appointmentType,
      visitReason: entity.visitReason,
      chiefComplaint: entity.chiefComplaint,
      priority: entity.priority,
      status: entity.status,
      cancellationReason: entity.cancellationReason,
      cancelledBy: entity.cancelledBy,
      tokenNumber: entity.tokenNumber,
    );
  }

  /// Converts this model to an entity
  AppointmentEntity toEntity() {
    return AppointmentEntity(
      patientId: patientId,
      doctorId: doctorId,
      departmentId: departmentId,
      branchId: branchId,
      familyMemberId: familyMemberId,
      appointmentDate: appointmentDate,
      slotStartTime: slotStartTime,
      slotEndTime: slotEndTime,
      bookingSource: bookingSource,
      appointmentType: appointmentType,
      visitReason: visitReason,
      chiefComplaint: chiefComplaint,
      priority: priority,
      status: status,
      cancellationReason: cancellationReason,
      cancelledBy: cancelledBy,
      tokenNumber: tokenNumber,
    );
  }

  /// Creates an empty AppointmentModel
  factory AppointmentModel.empty() {
    return AppointmentModel(
      patientId: '',
      doctorId: '',
      departmentId: '',
      branchId: '',
      familyMemberId: '',
      appointmentDate: '',
      slotStartTime: '',
      slotEndTime: '',
      bookingSource: '',
      appointmentType: '',
      visitReason: '',
      chiefComplaint: '',
      priority: '',
      status: '',
      cancellationReason: '',
      cancelledBy: '',
      tokenNumber: 0,
    );
  }

  /// Creates a copy with updated fields
  @override
  AppointmentModel copyWith({
    String? patientId,
    String? doctorId,
    String? departmentId,
    String? branchId,
    String? familyMemberId,
    String? appointmentDate,
    String? slotStartTime,
    String? slotEndTime,
    String? bookingSource,
    String? appointmentType,
    String? visitReason,
    String? chiefComplaint,
    String? priority,
    String? status,
    String? cancellationReason,
    String? cancelledBy,
    int? tokenNumber,
  }) {
    return AppointmentModel(
      patientId: patientId ?? this.patientId,
      doctorId: doctorId ?? this.doctorId,
      departmentId: departmentId ?? this.departmentId,
      branchId: branchId ?? this.branchId,
      familyMemberId: familyMemberId ?? this.familyMemberId,
      appointmentDate: appointmentDate ?? this.appointmentDate,
      slotStartTime: slotStartTime ?? this.slotStartTime,
      slotEndTime: slotEndTime ?? this.slotEndTime,
      bookingSource: bookingSource ?? this.bookingSource,
      appointmentType: appointmentType ?? this.appointmentType,
      visitReason: visitReason ?? this.visitReason,
      chiefComplaint: chiefComplaint ?? this.chiefComplaint,
      priority: priority ?? this.priority,
      status: status ?? this.status,
      cancellationReason: cancellationReason ?? this.cancellationReason,
      cancelledBy: cancelledBy ?? this.cancelledBy,
      tokenNumber: tokenNumber ?? this.tokenNumber,
    );
  }
}
