/// Department Model
///
/// Data model that extends DepartmentEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/department_entity.dart';

/// Department data model with JSON serialization
class DepartmentModel extends DepartmentEntity {
  const DepartmentModel({
    required super.name,
    required super.code,
    required super.description,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => code.isNotEmpty ? code : name;

  /// Creates a DepartmentModel from JSON map
  factory DepartmentModel.fromJson(Map<String, dynamic> json) {
    return DepartmentModel(
      name: json['name']?.toString() ?? '',
      code: json['code']?.toString() ?? '',
      description: json['description']?.toString() ?? '',
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {'name': name, 'code': code, 'description': description};
  }

  /// Creates a DepartmentModel from a DepartmentEntity
  factory DepartmentModel.fromEntity(DepartmentEntity entity) {
    return DepartmentModel(
      name: entity.name,
      code: entity.code,
      description: entity.description,
    );
  }

  /// Converts this model to an entity
  DepartmentEntity toEntity() {
    return DepartmentEntity(name: name, code: code, description: description);
  }

  /// Creates an empty DepartmentModel
  factory DepartmentModel.empty() {
    return DepartmentModel(name: '', code: '', description: '');
  }

  /// Creates a copy with updated fields
  @override
  DepartmentModel copyWith({String? name, String? code, String? description}) {
    return DepartmentModel(
      name: name ?? this.name,
      code: code ?? this.code,
      description: description ?? this.description,
    );
  }
}
