/// DoctorSchedule Model
///
/// Data model that extends DoctorScheduleEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/doctor_schedule_entity.dart';

/// DoctorSchedule data model with JSON serialization
class DoctorScheduleModel extends DoctorScheduleEntity {
  const DoctorScheduleModel({
    required super.doctorId,
    required super.branchId,
    required super.slotStartTime,
    required super.slotEndTime,
    required super.effectiveFrom,
    required super.effectiveUntil,
    required super.dayOfWeek,
    required super.maxTokens,
    required super.isActive,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => '$doctorId-$dayOfWeek-$slotStartTime-$slotEndTime';

  /// Creates a DoctorScheduleModel from JSON map
  factory DoctorScheduleModel.fromJson(Map<String, dynamic> json) {
    return DoctorScheduleModel(
      doctorId: json['doctor_id']?.toString() ?? '',
      branchId: json['branch_id']?.toString() ?? '',
      slotStartTime: json['slot_start_time']?.toString() ?? '',
      slotEndTime: json['slot_end_time']?.toString() ?? '',
      effectiveFrom: json['effective_from']?.toString() ?? '',
      effectiveUntil: json['effective_until']?.toString() ?? '',
      dayOfWeek: json['day_of_week'] as int? ?? 0,
      maxTokens: json['max_tokens'] as int? ?? 0,
      isActive:
          json['is_active'] as bool? ?? json['isActive'] as bool? ?? false,
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'doctor_id': doctorId,
      'branch_id': branchId,
      'slot_start_time': slotStartTime,
      'slot_end_time': slotEndTime,
      'effective_from': effectiveFrom,
      'effective_until': effectiveUntil,
      'day_of_week': dayOfWeek,
      'max_tokens': maxTokens,
      'is_active': isActive,
    };
  }

  /// Creates a DoctorScheduleModel from a DoctorScheduleEntity
  factory DoctorScheduleModel.fromEntity(DoctorScheduleEntity entity) {
    return DoctorScheduleModel(
      doctorId: entity.doctorId,
      branchId: entity.branchId,
      slotStartTime: entity.slotStartTime,
      slotEndTime: entity.slotEndTime,
      effectiveFrom: entity.effectiveFrom,
      effectiveUntil: entity.effectiveUntil,
      dayOfWeek: entity.dayOfWeek,
      maxTokens: entity.maxTokens,
      isActive: entity.isActive,
    );
  }

  /// Converts this model to an entity
  DoctorScheduleEntity toEntity() {
    return DoctorScheduleEntity(
      doctorId: doctorId,
      branchId: branchId,
      slotStartTime: slotStartTime,
      slotEndTime: slotEndTime,
      effectiveFrom: effectiveFrom,
      effectiveUntil: effectiveUntil,
      dayOfWeek: dayOfWeek,
      maxTokens: maxTokens,
      isActive: isActive,
    );
  }

  /// Creates an empty DoctorScheduleModel
  factory DoctorScheduleModel.empty() {
    return DoctorScheduleModel(
      doctorId: '',
      branchId: '',
      slotStartTime: '',
      slotEndTime: '',
      effectiveFrom: '',
      effectiveUntil: '',
      dayOfWeek: 0,
      maxTokens: 0,
      isActive: false,
    );
  }

  /// Creates a copy with updated fields
  @override
  DoctorScheduleModel copyWith({
    String? doctorId,
    String? branchId,
    String? slotStartTime,
    String? slotEndTime,
    String? effectiveFrom,
    String? effectiveUntil,
    int? dayOfWeek,
    int? maxTokens,
    bool? isActive,
  }) {
    return DoctorScheduleModel(
      doctorId: doctorId ?? this.doctorId,
      branchId: branchId ?? this.branchId,
      slotStartTime: slotStartTime ?? this.slotStartTime,
      slotEndTime: slotEndTime ?? this.slotEndTime,
      effectiveFrom: effectiveFrom ?? this.effectiveFrom,
      effectiveUntil: effectiveUntil ?? this.effectiveUntil,
      dayOfWeek: dayOfWeek ?? this.dayOfWeek,
      maxTokens: maxTokens ?? this.maxTokens,
      isActive: isActive ?? this.isActive,
    );
  }
}
