/// Doctor Model
///
/// Data model that extends DoctorEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/doctor_entity.dart';

/// Doctor data model with JSON serialization
class DoctorModel extends DoctorEntity {
  const DoctorModel({
    required super.firstName,
    required super.lastName,
    required super.salutation,
    required super.genderCode,
    required super.specialization,
    required super.subSpecialization,
    required super.qualifications,
    required super.profilePhotoUrl,
    required super.mciRegistrationNumber,
    required super.experienceYears,
    required super.maxPatientsPerDay,
    required super.avgConsultationMin,
    required super.consultationFee,
    required super.followUpFee,
    required super.isAvailableOnline,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => mciRegistrationNumber.isNotEmpty
      ? mciRegistrationNumber
      : '$firstName-$lastName-$specialization';

  /// Creates a DoctorModel from JSON map
  factory DoctorModel.fromJson(Map<String, dynamic> json) {
    return DoctorModel(
      firstName: json['first_name']?.toString() ?? '',
      lastName: json['last_name']?.toString() ?? '',
      salutation: json['salutation']?.toString() ?? '',
      genderCode: json['gender_code']?.toString() ?? '',
      specialization: json['specialization']?.toString() ?? '',
      subSpecialization: json['sub_specialization']?.toString() ?? '',
      qualifications: json['qualifications']?.toString() ?? '',
      profilePhotoUrl: json['profile_photo_url']?.toString() ?? '',
      mciRegistrationNumber: json['mci_registration_number']?.toString() ?? '',
      experienceYears: json['experience_years'] as int? ?? 0,
      maxPatientsPerDay: json['max_patients_per_day'] as int? ?? 0,
      avgConsultationMin: json['avg_consultation_min'] as int? ?? 0,
      consultationFee:
          double.tryParse(json['consultation_fee']?.toString() ?? '') ?? 0.0,
      followUpFee:
          double.tryParse(json['follow_up_fee']?.toString() ?? '') ?? 0.0,
      isAvailableOnline:
          json['is_available_online'] as bool? ??
          json['isAvailableOnline'] as bool? ??
          false,
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'first_name': firstName,
      'last_name': lastName,
      'salutation': salutation,
      'gender_code': genderCode,
      'specialization': specialization,
      'sub_specialization': subSpecialization,
      'qualifications': qualifications,
      'profile_photo_url': profilePhotoUrl,
      'mci_registration_number': mciRegistrationNumber,
      'experience_years': experienceYears,
      'max_patients_per_day': maxPatientsPerDay,
      'avg_consultation_min': avgConsultationMin,
      'consultation_fee': consultationFee,
      'follow_up_fee': followUpFee,
      'is_available_online': isAvailableOnline,
    };
  }

  /// Creates a DoctorModel from a DoctorEntity
  factory DoctorModel.fromEntity(DoctorEntity entity) {
    return DoctorModel(
      firstName: entity.firstName,
      lastName: entity.lastName,
      salutation: entity.salutation,
      genderCode: entity.genderCode,
      specialization: entity.specialization,
      subSpecialization: entity.subSpecialization,
      qualifications: entity.qualifications,
      profilePhotoUrl: entity.profilePhotoUrl,
      mciRegistrationNumber: entity.mciRegistrationNumber,
      experienceYears: entity.experienceYears,
      maxPatientsPerDay: entity.maxPatientsPerDay,
      avgConsultationMin: entity.avgConsultationMin,
      consultationFee: entity.consultationFee,
      followUpFee: entity.followUpFee,
      isAvailableOnline: entity.isAvailableOnline,
    );
  }

  /// Converts this model to an entity
  DoctorEntity toEntity() {
    return DoctorEntity(
      firstName: firstName,
      lastName: lastName,
      salutation: salutation,
      genderCode: genderCode,
      specialization: specialization,
      subSpecialization: subSpecialization,
      qualifications: qualifications,
      profilePhotoUrl: profilePhotoUrl,
      mciRegistrationNumber: mciRegistrationNumber,
      experienceYears: experienceYears,
      maxPatientsPerDay: maxPatientsPerDay,
      avgConsultationMin: avgConsultationMin,
      consultationFee: consultationFee,
      followUpFee: followUpFee,
      isAvailableOnline: isAvailableOnline,
    );
  }

  /// Creates an empty DoctorModel
  factory DoctorModel.empty() {
    return DoctorModel(
      firstName: '',
      lastName: '',
      salutation: '',
      genderCode: '',
      specialization: '',
      subSpecialization: '',
      qualifications: '',
      profilePhotoUrl: '',
      mciRegistrationNumber: '',
      experienceYears: 0,
      maxPatientsPerDay: 0,
      avgConsultationMin: 0,
      consultationFee: 0.0,
      followUpFee: 0.0,
      isAvailableOnline: false,
    );
  }

  /// Creates a copy with updated fields
  @override
  DoctorModel copyWith({
    String? firstName,
    String? lastName,
    String? salutation,
    String? genderCode,
    String? specialization,
    String? subSpecialization,
    String? qualifications,
    String? profilePhotoUrl,
    String? mciRegistrationNumber,
    int? experienceYears,
    int? maxPatientsPerDay,
    int? avgConsultationMin,
    double? consultationFee,
    double? followUpFee,
    bool? isAvailableOnline,
  }) {
    return DoctorModel(
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      salutation: salutation ?? this.salutation,
      genderCode: genderCode ?? this.genderCode,
      specialization: specialization ?? this.specialization,
      subSpecialization: subSpecialization ?? this.subSpecialization,
      qualifications: qualifications ?? this.qualifications,
      profilePhotoUrl: profilePhotoUrl ?? this.profilePhotoUrl,
      mciRegistrationNumber:
          mciRegistrationNumber ?? this.mciRegistrationNumber,
      experienceYears: experienceYears ?? this.experienceYears,
      maxPatientsPerDay: maxPatientsPerDay ?? this.maxPatientsPerDay,
      avgConsultationMin: avgConsultationMin ?? this.avgConsultationMin,
      consultationFee: consultationFee ?? this.consultationFee,
      followUpFee: followUpFee ?? this.followUpFee,
      isAvailableOnline: isAvailableOnline ?? this.isAvailableOnline,
    );
  }
}
