/// HospitalBranch Model
///
/// Data model that extends HospitalBranchEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/hospital_branch_entity.dart';

/// HospitalBranch data model with JSON serialization
class HospitalBranchModel extends HospitalBranchEntity {
  const HospitalBranchModel({
    required super.branchName,
    required super.branchCode,
    required super.addressLine1,
    required super.city,
    required super.state,
    required super.pincode,
    required super.phone,
    required super.email,
    required super.latitude,
    required super.longitude,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => branchCode.isNotEmpty ? branchCode : branchName;

  /// Creates a HospitalBranchModel from JSON map
  factory HospitalBranchModel.fromJson(Map<String, dynamic> json) {
    return HospitalBranchModel(
      branchName: json['branch_name']?.toString() ?? '',
      branchCode: json['branch_code']?.toString() ?? '',
      addressLine1: json['address_line1']?.toString() ?? '',
      city: json['city']?.toString() ?? '',
      state: json['state']?.toString() ?? '',
      pincode: json['pincode']?.toString() ?? '',
      phone: json['phone']?.toString() ?? '',
      email: json['email']?.toString() ?? '',
      latitude: double.tryParse(json['latitude']?.toString() ?? '') ?? 0.0,
      longitude: double.tryParse(json['longitude']?.toString() ?? '') ?? 0.0,
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'branch_name': branchName,
      'branch_code': branchCode,
      'address_line1': addressLine1,
      'city': city,
      'state': state,
      'pincode': pincode,
      'phone': phone,
      'email': email,
      'latitude': latitude,
      'longitude': longitude,
    };
  }

  /// Creates a HospitalBranchModel from a HospitalBranchEntity
  factory HospitalBranchModel.fromEntity(HospitalBranchEntity entity) {
    return HospitalBranchModel(
      branchName: entity.branchName,
      branchCode: entity.branchCode,
      addressLine1: entity.addressLine1,
      city: entity.city,
      state: entity.state,
      pincode: entity.pincode,
      phone: entity.phone,
      email: entity.email,
      latitude: entity.latitude,
      longitude: entity.longitude,
    );
  }

  /// Converts this model to an entity
  HospitalBranchEntity toEntity() {
    return HospitalBranchEntity(
      branchName: branchName,
      branchCode: branchCode,
      addressLine1: addressLine1,
      city: city,
      state: state,
      pincode: pincode,
      phone: phone,
      email: email,
      latitude: latitude,
      longitude: longitude,
    );
  }

  /// Creates an empty HospitalBranchModel
  factory HospitalBranchModel.empty() {
    return HospitalBranchModel(
      branchName: '',
      branchCode: '',
      addressLine1: '',
      city: '',
      state: '',
      pincode: '',
      phone: '',
      email: '',
      latitude: 0.0,
      longitude: 0.0,
    );
  }

  /// Creates a copy with updated fields
  @override
  HospitalBranchModel copyWith({
    String? branchName,
    String? branchCode,
    String? addressLine1,
    String? city,
    String? state,
    String? pincode,
    String? phone,
    String? email,
    double? latitude,
    double? longitude,
  }) {
    return HospitalBranchModel(
      branchName: branchName ?? this.branchName,
      branchCode: branchCode ?? this.branchCode,
      addressLine1: addressLine1 ?? this.addressLine1,
      city: city ?? this.city,
      state: state ?? this.state,
      pincode: pincode ?? this.pincode,
      phone: phone ?? this.phone,
      email: email ?? this.email,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
    );
  }
}
