/// QueueStatus Model
///
/// Data model that extends QueueStatusEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/queue_status_entity.dart';

/// QueueStatus data model with JSON serialization
class QueueStatusModel extends QueueStatusEntity {
  const QueueStatusModel({
    required super.doctorId,
    required super.queueDate,
    required super.status,
    required super.currentToken,
    required super.totalTokensIssued,
    required super.avgWaitMinutes,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => '$doctorId-$queueDate';

  /// Creates a QueueStatusModel from JSON map
  factory QueueStatusModel.fromJson(Map<String, dynamic> json) {
    return QueueStatusModel(
      doctorId: json['doctor_id']?.toString() ?? '',
      queueDate: json['queue_date']?.toString() ?? '',
      status: json['status']?.toString() ?? '',
      currentToken: json['current_token'] as int? ?? 0,
      totalTokensIssued: json['total_tokens_issued'] as int? ?? 0,
      avgWaitMinutes: json['avg_wait_minutes'] as int? ?? 0,
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'doctor_id': doctorId,
      'queue_date': queueDate,
      'status': status,
      'current_token': currentToken,
      'total_tokens_issued': totalTokensIssued,
      'avg_wait_minutes': avgWaitMinutes,
    };
  }

  /// Creates a QueueStatusModel from a QueueStatusEntity
  factory QueueStatusModel.fromEntity(QueueStatusEntity entity) {
    return QueueStatusModel(
      doctorId: entity.doctorId,
      queueDate: entity.queueDate,
      status: entity.status,
      currentToken: entity.currentToken,
      totalTokensIssued: entity.totalTokensIssued,
      avgWaitMinutes: entity.avgWaitMinutes,
    );
  }

  /// Converts this model to an entity
  QueueStatusEntity toEntity() {
    return QueueStatusEntity(
      doctorId: doctorId,
      queueDate: queueDate,
      status: status,
      currentToken: currentToken,
      totalTokensIssued: totalTokensIssued,
      avgWaitMinutes: avgWaitMinutes,
    );
  }

  /// Creates an empty QueueStatusModel
  factory QueueStatusModel.empty() {
    return QueueStatusModel(
      doctorId: '',
      queueDate: '',
      status: '',
      currentToken: 0,
      totalTokensIssued: 0,
      avgWaitMinutes: 0,
    );
  }

  /// Creates a copy with updated fields
  @override
  QueueStatusModel copyWith({
    String? doctorId,
    String? queueDate,
    String? status,
    int? currentToken,
    int? totalTokensIssued,
    int? avgWaitMinutes,
  }) {
    return QueueStatusModel(
      doctorId: doctorId ?? this.doctorId,
      queueDate: queueDate ?? this.queueDate,
      status: status ?? this.status,
      currentToken: currentToken ?? this.currentToken,
      totalTokensIssued: totalTokensIssued ?? this.totalTokensIssued,
      avgWaitMinutes: avgWaitMinutes ?? this.avgWaitMinutes,
    );
  }
}
