/// AppointmentPreview Model
///
/// Data model that extends AppointmentPreviewEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/appointment_preview_entity.dart';

/// AppointmentPreview data model with JSON serialization
class AppointmentPreviewModel extends AppointmentPreviewEntity {
  const AppointmentPreviewModel({
    required super.appointmentId,
    required super.doctorName,
    required super.departmentName,
    required super.hospitalBranch,
    required super.appointmentDate,
    required super.slotTime,
    required super.status,
    required super.tokenNumber,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => appointmentId;

  /// Creates a AppointmentPreviewModel from JSON map
  factory AppointmentPreviewModel.fromJson(Map<String, dynamic> json) {
    return AppointmentPreviewModel(
      appointmentId: json['appointment_id']?.toString() ?? '',
      doctorName: json['doctor_name']?.toString() ?? '',
      departmentName: json['department_name']?.toString() ?? '',
      hospitalBranch: json['hospital_branch']?.toString() ?? '',
      appointmentDate: json['appointment_date']?.toString() ?? '',
      slotTime: json['slot_time']?.toString() ?? '',
      status: json['status']?.toString() ?? '',
      tokenNumber: json['token_number'] as int? ?? 0,
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'appointment_id': appointmentId,
      'doctor_name': doctorName,
      'department_name': departmentName,
      'hospital_branch': hospitalBranch,
      'appointment_date': appointmentDate,
      'slot_time': slotTime,
      'status': status,
      'token_number': tokenNumber,
    };
  }

  /// Creates a AppointmentPreviewModel from a AppointmentPreviewEntity
  factory AppointmentPreviewModel.fromEntity(AppointmentPreviewEntity entity) {
    return AppointmentPreviewModel(
      appointmentId: entity.appointmentId,
      doctorName: entity.doctorName,
      departmentName: entity.departmentName,
      hospitalBranch: entity.hospitalBranch,
      appointmentDate: entity.appointmentDate,
      slotTime: entity.slotTime,
      status: entity.status,
      tokenNumber: entity.tokenNumber,
    );
  }

  /// Converts this model to an entity
  AppointmentPreviewEntity toEntity() {
    return AppointmentPreviewEntity(
      appointmentId: appointmentId,
      doctorName: doctorName,
      departmentName: departmentName,
      hospitalBranch: hospitalBranch,
      appointmentDate: appointmentDate,
      slotTime: slotTime,
      status: status,
      tokenNumber: tokenNumber,
    );
  }

  /// Creates an empty AppointmentPreviewModel
  factory AppointmentPreviewModel.empty() {
    return AppointmentPreviewModel(
      appointmentId: '',
      doctorName: '',
      departmentName: '',
      hospitalBranch: '',
      appointmentDate: '',
      slotTime: '',
      status: '',
      tokenNumber: 0,
    );
  }

  /// Creates a copy with updated fields
  @override
  AppointmentPreviewModel copyWith({
    String? appointmentId,
    String? doctorName,
    String? departmentName,
    String? hospitalBranch,
    String? appointmentDate,
    String? slotTime,
    String? status,
    int? tokenNumber,
  }) {
    return AppointmentPreviewModel(
      appointmentId: appointmentId ?? this.appointmentId,
      doctorName: doctorName ?? this.doctorName,
      departmentName: departmentName ?? this.departmentName,
      hospitalBranch: hospitalBranch ?? this.hospitalBranch,
      appointmentDate: appointmentDate ?? this.appointmentDate,
      slotTime: slotTime ?? this.slotTime,
      status: status ?? this.status,
      tokenNumber: tokenNumber ?? this.tokenNumber,
    );
  }
}
