/// HealthAlert Model
///
/// Data model that extends HealthAlertEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/health_alert_entity.dart';

/// HealthAlert data model with JSON serialization
class HealthAlertModel extends HealthAlertEntity {
  const HealthAlertModel({
    required super.title,
    required super.message,
    required super.alertType,
    required super.priority,
  });

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => '$alertType-$priority-$title';

  /// Creates a HealthAlertModel from JSON map
  factory HealthAlertModel.fromJson(Map<String, dynamic> json) {
    return HealthAlertModel(
      title: json['title']?.toString() ?? '',
      message: json['message']?.toString() ?? '',
      alertType: json['alert_type']?.toString() ?? '',
      priority: json['priority']?.toString() ?? '',
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'message': message,
      'alert_type': alertType,
      'priority': priority,
    };
  }

  /// Creates a HealthAlertModel from a HealthAlertEntity
  factory HealthAlertModel.fromEntity(HealthAlertEntity entity) {
    return HealthAlertModel(
      title: entity.title,
      message: entity.message,
      alertType: entity.alertType,
      priority: entity.priority,
    );
  }

  /// Converts this model to an entity
  HealthAlertEntity toEntity() {
    return HealthAlertEntity(
      title: title,
      message: message,
      alertType: alertType,
      priority: priority,
    );
  }

  /// Creates an empty HealthAlertModel
  factory HealthAlertModel.empty() {
    return HealthAlertModel(
      title: '',
      message: '',
      alertType: '',
      priority: '',
    );
  }

  /// Creates a copy with updated fields
  @override
  HealthAlertModel copyWith({
    String? title,
    String? message,
    String? alertType,
    String? priority,
  }) {
    return HealthAlertModel(
      title: title ?? this.title,
      message: message ?? this.message,
      alertType: alertType ?? this.alertType,
      priority: priority ?? this.priority,
    );
  }
}
