/// HomeSummary Model
///
/// Data model that extends HomeSummaryEntity.
/// Handles JSON serialization/deserialization for API communication.
library;

import '../../domain/entities/home_summary_entity.dart';

/// HomeSummary data model with JSON serialization
class HomeSummaryModel extends HomeSummaryEntity {
  const HomeSummaryModel({required super.summaryTitle});

  // Local cache helpers generated by CLI expect an `id` field.
  String get id => summaryTitle;

  /// Creates a HomeSummaryModel from JSON map
  factory HomeSummaryModel.fromJson(Map<String, dynamic> json) {
    return HomeSummaryModel(
      summaryTitle: json['summary_title']?.toString() ?? '',
    );
  }

  /// Converts the model to a JSON map
  Map<String, dynamic> toJson() {
    return {'summary_title': summaryTitle};
  }

  /// Creates a HomeSummaryModel from a HomeSummaryEntity
  factory HomeSummaryModel.fromEntity(HomeSummaryEntity entity) {
    return HomeSummaryModel(summaryTitle: entity.summaryTitle);
  }

  /// Converts this model to an entity
  HomeSummaryEntity toEntity() {
    return HomeSummaryEntity(summaryTitle: summaryTitle);
  }

  /// Creates an empty HomeSummaryModel
  factory HomeSummaryModel.empty() {
    return HomeSummaryModel(summaryTitle: '');
  }

  /// Creates a copy with updated fields
  @override
  HomeSummaryModel copyWith({String? summaryTitle}) {
    return HomeSummaryModel(summaryTitle: summaryTitle ?? this.summaryTitle);
  }
}
